apiVersion: 1

datasources:
  - name: cv-stream-timescaledb
    uid: cv-stream-timescaledb
    type: postgres
    access: proxy
    url: ${GRAFANA_PG_HOST}:${GRAFANA_PG_PORT}
    database: ${GRAFANA_PG_DATABASE}
    user: ${GRAFANA_PG_USER}
    secureJsonData:
      password: ${GRAFANA_PG_PASSWORD}
    jsonData:
      database: ${GRAFANA_PG_DATABASE}
      postgresVersion: 1400
      sslmode: ${GRAFANA_PG_SSLMODE}
      timescaledb: true
    editable: true
