CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS device (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_name varchar(120) NOT NULL,
  owner varchar(120) NOT NULL,
  stream_protocol varchar(32) NOT NULL DEFAULT 'http_mjpeg',
  rtsp_url text,
  rtmp_url text,
  http_mjpeg_url text,
  register_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT device_protocol_check
    CHECK (stream_protocol IN ('http_mjpeg', 'rtsp', 'rtmp', 'camera', 'file')),
  CONSTRAINT device_name_owner_unique UNIQUE (device_name, owner)
);

CREATE TABLE IF NOT EXISTS cv_task (
  task_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id integer NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  task_name varchar(160) NOT NULL,
  model_name varchar(120) NOT NULL DEFAULT 'yolov8n.pt',
  confidence_threshold double precision NOT NULL DEFAULT 0.5,
  frame_interval integer NOT NULL DEFAULT 10,
  source_kind varchar(32) NOT NULL DEFAULT 'http_mjpeg',
  source_url text,
  inference_endpoint text,
  status varchar(32) NOT NULL DEFAULT 'configured',
  start_time timestamptz,
  end_time timestamptz,
  create_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cv_task_confidence_check
    CHECK (confidence_threshold >= 0 AND confidence_threshold <= 1),
  CONSTRAINT cv_task_frame_interval_check
    CHECK (frame_interval > 0),
  CONSTRAINT cv_task_source_kind_check
    CHECK (source_kind IN ('http_mjpeg', 'rtsp', 'rtmp', 'camera', 'file')),
  CONSTRAINT cv_task_status_check
    CHECK (status IN ('configured', 'running', 'stopped', 'failed')),
  CONSTRAINT cv_task_device_name_unique UNIQUE (device_id, task_name)
);

CREATE TABLE IF NOT EXISTS cv_result_meta (
  result_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id integer NOT NULL REFERENCES cv_task(task_id) ON DELETE CASCADE,
  object_class varchar(80) NOT NULL,
  avg_confidence double precision NOT NULL,
  total_count integer NOT NULL,
  stat_time timestamptz NOT NULL,
  stat_window_seconds integer NOT NULL DEFAULT 60,
  create_time timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT cv_result_meta_confidence_check
    CHECK (avg_confidence >= 0 AND avg_confidence <= 1),
  CONSTRAINT cv_result_meta_total_count_check
    CHECK (total_count >= 0),
  CONSTRAINT cv_result_meta_window_check
    CHECK (stat_window_seconds > 0),
  CONSTRAINT cv_result_meta_unique UNIQUE (task_id, object_class, stat_time, stat_window_seconds)
);

CREATE TABLE IF NOT EXISTS cv_detection_stream (
  time timestamptz NOT NULL,
  detection_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_id integer NOT NULL REFERENCES device(id) ON DELETE CASCADE,
  task_id integer NOT NULL REFERENCES cv_task(task_id) ON DELETE CASCADE,
  object_class varchar(80) NOT NULL,
  confidence double precision NOT NULL,
  bbox_x1 double precision,
  bbox_y1 double precision,
  bbox_x2 double precision,
  bbox_y2 double precision,
  bbox_center_x double precision,
  bbox_center_y double precision,
  frame_index bigint,
  source_kind varchar(32) NOT NULL DEFAULT 'http_mjpeg',
  inference_device varchar(32) NOT NULL DEFAULT 'auto',
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (time, detection_id),
  CONSTRAINT cv_detection_confidence_check
    CHECK (confidence >= 0 AND confidence <= 1),
  CONSTRAINT cv_detection_source_kind_check
    CHECK (source_kind IN ('http_mjpeg', 'rtsp', 'rtmp', 'camera', 'file'))
);

SELECT create_hypertable(
  'cv_detection_stream',
  'time',
  chunk_time_interval => INTERVAL '1 hour',
  if_not_exists => TRUE
);

CREATE INDEX IF NOT EXISTS idx_cv_task_device_id
  ON cv_task (device_id);

CREATE INDEX IF NOT EXISTS idx_cv_result_meta_task_time
  ON cv_result_meta (task_id, stat_time DESC);

CREATE INDEX IF NOT EXISTS idx_cv_detection_device_time
  ON cv_detection_stream (device_id, time DESC);

CREATE INDEX IF NOT EXISTS idx_cv_detection_task_time
  ON cv_detection_stream (task_id, time DESC);

CREATE INDEX IF NOT EXISTS idx_cv_detection_object_time
  ON cv_detection_stream (object_class, time DESC);

CREATE MATERIALIZED VIEW IF NOT EXISTS minutely_object_stats
WITH (timescaledb.continuous) AS
SELECT
  time_bucket('1 minute', time) AS bucket,
  device_id,
  task_id,
  object_class,
  count(*) AS detection_count,
  avg(confidence) AS avg_confidence
FROM cv_detection_stream
GROUP BY bucket, device_id, task_id, object_class
WITH NO DATA;

INSERT INTO device (
  device_name,
  owner,
  stream_protocol,
  http_mjpeg_url,
  rtsp_url,
  rtmp_url
) VALUES (
  'Android IP Webcam',
  'edge-user',
  'http_mjpeg',
  'http://PHONE_IP:8080/video',
  'rtsp://SERVER_HOST:8554/mystream',
  'rtmp://SERVER_HOST:1935/live/mystream'
)
ON CONFLICT (device_name, owner) DO UPDATE SET
  stream_protocol = EXCLUDED.stream_protocol,
  http_mjpeg_url = EXCLUDED.http_mjpeg_url,
  rtsp_url = EXCLUDED.rtsp_url,
  rtmp_url = EXCLUDED.rtmp_url;

WITH target_device AS (
  SELECT id
  FROM device
  WHERE device_name = 'Android IP Webcam'
    AND owner = 'edge-user'
  LIMIT 1
)
INSERT INTO cv_task (
  device_id,
  task_name,
  model_name,
  confidence_threshold,
  frame_interval,
  source_kind,
  source_url,
  status,
  start_time
)
SELECT
  id,
  'YOLOv8n 实时目标检测',
  'yolov8n.pt',
  0.5,
  10,
  'http_mjpeg',
  'http://PHONE_IP:8080/video',
  'configured',
  now()
FROM target_device
ON CONFLICT (device_id, task_name) DO UPDATE SET
  model_name = EXCLUDED.model_name,
  confidence_threshold = EXCLUDED.confidence_threshold,
  frame_interval = EXCLUDED.frame_interval,
  source_kind = EXCLUDED.source_kind,
  source_url = EXCLUDED.source_url;

WITH target_device AS (
  SELECT id
  FROM device
  WHERE device_name = 'Android IP Webcam'
    AND owner = 'edge-user'
  LIMIT 1
)
INSERT INTO cv_task (
  device_id,
  task_name,
  model_name,
  confidence_threshold,
  frame_interval,
  source_kind,
  source_url,
  status,
  start_time
)
SELECT
  id,
  'YOLOv8n 低置信度复核',
  'yolov8n.pt',
  0.35,
  15,
  'http_mjpeg',
  'http://PHONE_IP:8080/video',
  'configured',
  now()
FROM target_device
ON CONFLICT (device_id, task_name) DO UPDATE SET
  model_name = EXCLUDED.model_name,
  confidence_threshold = EXCLUDED.confidence_threshold,
  frame_interval = EXCLUDED.frame_interval,
  source_kind = EXCLUDED.source_kind,
  source_url = EXCLUDED.source_url;

WITH target_task AS (
  SELECT task_id
  FROM cv_task
  WHERE task_name = 'YOLOv8n 实时目标检测'
  LIMIT 1
)
INSERT INTO cv_result_meta (
  task_id,
  object_class,
  avg_confidence,
  total_count,
  stat_time,
  stat_window_seconds
)
SELECT
  task_id,
  'person',
  0.82,
  12,
  date_trunc('minute', now()),
  60
FROM target_task
ON CONFLICT (task_id, object_class, stat_time, stat_window_seconds) DO UPDATE SET
  avg_confidence = EXCLUDED.avg_confidence,
  total_count = EXCLUDED.total_count;
